version: "3"
services:
    db:
        image: postgres:13
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: mydatabase
        ports:
            - "5432:5432"
    app:
        build: .
        ports:
            - "3000:3000"
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydatabase
        depends_on:
            - db
